//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyThemAllModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public string Street { get; set; }
        public int HouseNo { get; set; }
        public int ApartmentNo { get; set; }
        public string City { get; set; }
        public int VoivodeshipId { get; set; }
        public int ClientId { get; set; }
    
        public virtual Voivodeship Voivodeship { get; set; }
    }
}
