//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyThemAllModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BuyThemAllEntities : DbContext
    {
        public BuyThemAllEntities()
            : base("name=BuyThemAllEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avalibility> Avalibilities { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryColor> CategoryColors { get; set; }
        public virtual DbSet<CategorySize> CategorySizes { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Graphic> Graphics { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderProduct> OrderProducts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ShipmentType> ShipmentTypes { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Voivodeship> Voivodeships { get; set; }
    }
}
