CREATE TABLE [dbo].[ShipmentType]
(
	[Id] INT IDENTITY PRIMARY KEY,
	[Code] NVARCHAR(10) NOT NULL UNIQUE,
	[Name] NVARCHAR(50) NOT NULL UNIQUE,
	[Price] FLOAT NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL
)
